#!/usr/bin/env python3
"""
Optional external brainstorm runner.

Default behavior is no-op/native. This script exists as a safe execution
boundary for projects that explicitly opt into an external brainstorm model.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

from common.config import get_brainstorm_config
from common.paths import get_repo_root


def _fallback_reason(config: dict[str, object]) -> list[str]:
    """Return reasons why external brainstorm must fall back to native."""
    reasons: list[str] = []
    if not bool(config.get("enabled")):
        return reasons
    if config.get("mode") != "external":
        return reasons

    if not str(config.get("provider", "")).strip():
        reasons.append("missing provider")
    if not str(config.get("base_url", "")).strip():
        reasons.append("missing base_url")
    if not str(config.get("model", "")).strip():
        reasons.append("missing model")

    api_key_env = str(config.get("api_key_env", "")).strip()
    if not api_key_env:
        reasons.append("missing api_key_env")
    elif not os.environ.get(api_key_env):
        reasons.append(f"environment variable {api_key_env} is not set")

    return reasons


def cmd_status(_args: argparse.Namespace) -> int:
    """Print resolved brainstorm execution status."""
    repo_root = get_repo_root()
    config = get_brainstorm_config(repo_root)
    fallback_reasons = _fallback_reason(config)
    payload = {
        "enabled": bool(config.get("enabled")),
        "mode": str(config.get("mode", "native")),
        "provider": str(config.get("provider", "")),
        "model": str(config.get("model", "")),
        "fallback_to_native": bool(fallback_reasons),
        "fallback_reasons": fallback_reasons,
    }
    print(json.dumps(payload, ensure_ascii=False))
    print(f"enabled: {str(payload['enabled']).lower()}")
    print(f"mode: {payload['mode']}")
    if payload["provider"]:
        print(f"provider: {payload['provider']}")
    if payload["model"]:
        print(f"model: {payload['model']}")
    print(f"fallback_to_native: {str(payload['fallback_to_native']).lower()}")
    for reason in fallback_reasons:
        print(reason)
    return 0


def _read_task_prd(repo_root: Path) -> str:
    """Best-effort read of the current task PRD for brainstorm context."""
    prd_path = _get_current_task_prd_path(repo_root)
    if not prd_path:
        return ""
    try:
        return prd_path.read_text(encoding="utf-8")
    except OSError:
        return ""


def _get_current_task_prd_path(repo_root: Path) -> Path | None:
    """Resolve the current task prd.md path from .current-task."""
    current_file = repo_root / ".trellis" / ".current-task"
    try:
        task_ref = current_file.read_text(encoding="utf-8").strip()
    except OSError:
        return None
    if not task_ref:
        return None
    task_ref = task_ref.replace("\\", "/")
    if task_ref.startswith(".trellis/"):
        return repo_root / task_ref / "prd.md"
    return repo_root / ".trellis" / "tasks" / task_ref / "prd.md"


def _write_external_draft_section(repo_root: Path, draft: str) -> None:
    """Append or replace the external brainstorm draft section in prd.md."""
    prd_path = _get_current_task_prd_path(repo_root)
    if not prd_path:
        return
    try:
        content = prd_path.read_text(encoding="utf-8")
    except OSError:
        return

    marker = "## External Brainstorm Draft"
    block = (
        f"{marker}\n\n"
        "_Generated by `.trellis/scripts/brainstorm_runner.py draft`. "
        "Review with the user before treating any item as confirmed._\n\n"
        f"{draft.strip()}\n"
    )

    if marker in content:
        prefix = content.split(marker, 1)[0].rstrip()
        updated = f"{prefix}\n\n{block}\n"
    else:
        updated = f"{content.rstrip()}\n\n{block}\n"

    prd_path.write_text(updated, encoding="utf-8")


def _build_prompt(goal: str, prd_text: str) -> str:
    """Build a compact external brainstorm prompt."""
    parts = [
        "You are an external brainstorm helper for Trellis.",
        "Return concise brainstorm material only.",
        "Output sections in plain text:",
        "1. Clarifying Questions",
        "2. Feasible Approaches",
        "3. Draft PRD Notes",
        "",
        f"User goal: {goal}",
    ]
    if prd_text.strip():
        parts.extend(["", "Existing PRD context:", prd_text.strip()])
    return "\n".join(parts)


def _extract_text(response_json: dict[str, object]) -> str:
    """Extract assistant text from an OpenAI-compatible response payload."""
    choices = response_json.get("choices")
    if not isinstance(choices, list) or not choices:
        return ""
    first = choices[0]
    if not isinstance(first, dict):
        return ""
    message = first.get("message")
    if not isinstance(message, dict):
        return ""
    content = message.get("content")
    return content.strip() if isinstance(content, str) else ""


def _call_openai_compatible(config: dict[str, object], goal: str, prd_text: str) -> str:
    """Call an OpenAI-compatible chat completions endpoint."""
    fake_response = os.environ.get("TRELLIS_BRAINSTORM_FAKE_RESPONSE")
    if fake_response:
        return _extract_text(json.loads(fake_response))

    base_url = str(config.get("base_url", "")).rstrip("/")
    model = str(config.get("model", "")).strip()
    api_key = os.environ[str(config.get("api_key_env", "")).strip()]
    raw_timeout = config.get("timeout_seconds", 60)
    timeout_seconds = int(raw_timeout) if isinstance(raw_timeout, (int, str)) else 60

    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": "You help draft brainstorm output for Trellis."},
            {"role": "user", "content": _build_prompt(goal, prd_text)},
        ],
    }
    req = urllib.request.Request(
        f"{base_url}/chat/completions",
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=timeout_seconds) as response:
        body = response.read().decode("utf-8")
    return _extract_text(json.loads(body))


def cmd_draft(args: argparse.Namespace) -> int:
    """Generate optional external brainstorm draft output.

    Failure never blocks the native brainstorm workflow. Instead, this command
    returns a fallback payload that tells the caller to continue natively.
    """
    repo_root = get_repo_root()
    config = get_brainstorm_config(repo_root)
    fallback_reasons = _fallback_reason(config)

    if fallback_reasons:
        print(
            json.dumps(
                {
                    "mode": "native_fallback",
                    "draft": "",
                    "fallback_reasons": fallback_reasons,
                },
                ensure_ascii=False,
                separators=(",", ":"),
            )
        )
        return 0

    try:
        prd_text = _read_task_prd(repo_root)
        draft = _call_openai_compatible(config, args.goal, prd_text)
        if not draft:
            raise ValueError("empty response from external brainstorm provider")
        _write_external_draft_section(repo_root, draft)
        print(
            json.dumps(
                {
                    "mode": "external",
                    "draft": draft,
                    "fallback_reasons": [],
                },
                ensure_ascii=False,
                separators=(",", ":"),
            )
        )
        return 0
    except (KeyError, ValueError, urllib.error.URLError, TimeoutError) as exc:
        print(
            json.dumps(
                {
                    "mode": "native_fallback",
                    "draft": "",
                    "fallback_reasons": [str(exc)],
                },
                ensure_ascii=False,
                separators=(",", ":"),
            )
        )
        return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Optional external brainstorm runner")
    subparsers = parser.add_subparsers(dest="command")

    subparsers.add_parser("status", help="Print resolved brainstorm runtime status")
    draft = subparsers.add_parser("draft", help="Generate optional external brainstorm draft")
    draft.add_argument("--goal", required=True, help="Current brainstorm goal")

    args = parser.parse_args()
    if args.command == "status":
        return cmd_status(args)
    if args.command == "draft":
        return cmd_draft(args)

    parser.print_help()
    return 1


if __name__ == "__main__":
    sys.exit(main())
